name: Deploy to VPS

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust this to your Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}

    - name: Deploy to VPS
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        VPS_IP: "57.128.212.249"
      run: |
        mkdir -p ~/.ssh
        echo "$VPS_SSH_KEY" > ~/.ssh/vps_key
        chmod 600 ~/.ssh/vps_key
        ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
        
        # Create a temporary directory for rsync exclusions
        mkdir -p ./rsync_exclude
        echo ".git" > ./rsync_exclude/exclude.txt
        echo "node_modules" >> ./rsync_exclude/exclude.txt
        
        # Use rsync to copy all files, excluding .git and node_modules
        rsync -avz --delete -e "ssh -i ~/.ssh/vps_key" --exclude-from=./rsync_exclude/exclude.txt ./ root@$VPS_IP:/var/www/batcore2/
        
        # Run remote commands
        ssh -i ~/.ssh/vps_key root@$VPS_IP "cp /home/.env /var/www/batcore2/.env && cd /var/www/batcore2 && npm i && npm run build && pm2 restart BATCOREWEB"
