name: Deploy to VPS

on:
  push:
    branches: [ main ]  # Adjust this if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust this based on your project's Node.js version
        cache: 'npm'  # Caches node_modules for faster builds

    - name: Install Dependencies
      run: npm ci

    - name: Build Application
      run: npm run build
      env:
        BETTERSTACK_API_KEY: ${{ secrets.BETTERSTACK_API_KEY }}

    - name: Deploy to VPS
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        VPS_IP: "57.128.212.249"
      run: |
        # Set up SSH key securely
        mkdir -p ~/.ssh
        echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/vps_key  # Ensure no carriage returns
        chmod 600 ~/.ssh/vps_key
        ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts
        
        # Deploy files using rsync (excludes unnecessary directories)
        rsync -avz --delete -e "ssh -i ~/.ssh/vps_key -o StrictHostKeyChecking=no" --exclude=".git" --exclude="node_modules" ./ root@"$VPS_IP":/var/www/batcore2/

        # SSH into VPS and restart services
        ssh -i ~/.ssh/vps_key root@"$VPS_IP" << 'EOF'
          cd /var/www/batcore2
          cp /home/.env .env
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm ci
          npm run build
          pm2 restart BATCOREWEB
        EOF
